session_date: "2026-01-05"
anchor_obd_time: "16:23:49.058"
anchor_road_video_s: 1.55
anchor_driver_video_s: 0.46
lane_width_m: 3.5
camera_shift_m: -0.30  # 10 cm LEFT of vehicle center (driver side)
resample_hz: 10
tlc_thr: 1.5
edge_thr: 0.20
attn_thr: 0.35
attn_min_s: 1.0
yaw_thr: 0.25
veh_thr: 3
obd_speed_col: "obd_obd_Vehicle Speed Sensor [km/h]"
obd_speed_min_kmh: 10.0
obd_decel_mps2_thr: 2.0
obd_decel_smooth_n: 3
polar_quality_thr: 70
bio_hr_z_thr: 1.0
bio_rmssd_z_thr: -1.0
bio_eeg_z_thr: 1.0
lane_color_red_ratio: 0.0
lane_color_yellow_ratio: 0.2
lane_color_red_m: 0.0
lane_color_yellow_m: 0.15
lane_color_eval_band_px: 6
lane_color_overlay: true
lane_roi_overlay: true
road_overlay_roi: true
road_overlay_lane_mask: false
road_overlay_color_mask: false
road_overlay_edges: false
road_overlay_hough: false
road_overlay_lane_points_detail: false
road_overlay_lane_dots: true
road_overlay_lane_eval: true
road_overlay_boxes: true
road_overlay_metrics: true
lane_line_cluster_gap_px: 12
lane_force_red_start_s: null
lane_force_red_end_s: null
lane_force_yellow_pad_s: 1.0
lane_force_windows_s:
  - [43.0, 43.0]
  - [46.0, 50.0]
lane_center_calib_start_s: 42.5
lane_center_calib_end_s: 43.5
lane_center_calib_side: "left"
lane_center_calib_edge_m: 0.0
lane_center_calib_min_lines: 3
lane_center_calib_apply_once: true
driver_overlay_bbox: true
driver_overlay_mesh: true
driver_overlay_contours: true
driver_overlay_iris: true
driver_overlay_pose: true
driver_overlay_gaze_line: true
driver_overlay_metrics: true
driver_overlay_gaze_bar: true
driver_overlay_blink: true
driver_gaze_low_thr: 0.5
driver_blink_ear_thr: 0.21
driver_yawn_mar_thr: 0.6
driver_gaze_line_scale_px: 60
driver_landmark_step: 8
overlay_style:
  road:
    lane_color_red: [0, 0, 255]
    lane_color_yellow: [0, 255, 255]
    lane_color_green: [0, 255, 0]
    lane_dot_radius: 3
    lane_extra_dot_radius: 2
    lane_line_thickness: 1
    lane_extra_step_detail: 5
    lane_extra_step_default: 7
    lane_eval_color: [255, 255, 255]
    lane_eval_thickness: 1
    lane_eval_band_color: [0, 255, 255]
    lane_eval_band_alpha: 0.12
    lane_edge_marker_color: [255, 255, 255]
    lane_edge_marker_thickness: 2
    lane_edge_marker_radius: 3
    lane_center_color: [255, 0, 255]
    lane_center_thickness: 1
    lane_center_radius: 3
    metrics_text_color: [255, 255, 255]
    metrics_text_pos: [10, 60]
    metrics_text_scale: 0.6
    metrics_text_thickness: 2
    lane_conf_text_color: [100, 100, 255]
    lane_conf_text_pos: [10, 30]
    lane_conf_text_scale: 0.6
    lane_conf_text_thickness: 2
    eval_text_color: [255, 255, 255]
    eval_text_pos: [10, 85]
    eval_text_line_gap: 25
    eval_text_scale: 0.5
    eval_text_thickness: 1
    box_color_vehicle: [0, 0, 255]
    box_color_vulnerable: [0, 255, 255]
    box_color_other: [255, 0, 0]
    box_thickness: 2
    box_label_scale: 0.5
    box_label_thickness: 1
    box_label_text_color: [255, 255, 255]
    box_label_pad_x: 2
    box_label_pad_y: 4
    box_label_y_offset: 6
    box_label_text_offset: [1, 2]
    roi_color: [0, 255, 255]
    roi_thickness: 2
    roi_text_color: [0, 255, 255]
    roi_text_scale: 0.6
    roi_text_thickness: 2
    roi_text_offset_x: 10
    roi_text_offset_y: -10
    mask_overlay_color: [0, 255, 255]
    mask_overlay_alpha: 0.35
    edges_overlay_color: [255, 0, 255]
    edges_overlay_alpha: 0.35
    hough_color: [0, 128, 255]
    hough_thickness: 2
  driver:
    bbox_good_color: [0, 255, 0]
    bbox_bad_color: [0, 0, 255]
    bbox_thickness: 2
    gaze_line_color: [255, 0, 255]
    gaze_line_thickness: 2
    pose_axis_x_color: [0, 0, 255]
    pose_axis_y_color: [0, 255, 0]
    pose_axis_z_color: [255, 0, 0]
    pose_axis_thickness: 2
    pose_axis_len: 60
    gaze_bar_border_color: [200, 200, 200]
    gaze_bar_border_thickness: 1
    gaze_bar_good_color: [0, 255, 0]
    gaze_bar_bad_color: [0, 0, 255]
    gaze_bar_height: 10
    gaze_bar_width_ratio: 0.25
    gaze_bar_x: 10
    gaze_bar_y_from_bottom: 20
    metrics_text_color: [255, 255, 255]
    metrics_text_pos: [10, 30]
    metrics_text_scale: 0.55
    metrics_text_thickness: 2
    blink_text_color: [255, 255, 255]
    blink_text_alert_color: [0, 0, 255]
    blink_text_pos: [10, 55]
    blink_text_scale: 0.55
    blink_text_thickness: 2
    face_conf_text_color: [0, 0, 255]
    face_conf_text_pos: [10, 30]
    face_conf_text_scale: 0.6
    face_conf_text_thickness: 2
    landmark_color: [0, 255, 255]
    landmark_radius: 1
